#!/usr/bin/python

"""Monkey.

Usage:
	monkey <command>...
"""
from docopt import docopt
import monkey

if __name__ == '__main__':
    cli = monkey.Monkey()
    arguments = docopt(__doc__, version='Monkey 0.1')
    cli.make(arguments)