#!/usr/bin/python

"""Monkey.

Usage:
  monkey (add|remove|setup|purge) <package_name> [<package_url>]
"""
from docopt import docopt
import monkey

if __name__ == '__main__':
    cli = monkey.Monkey()
    arguments = docopt(__doc__, version='Monkey 0.1')
    cli.do(arguments)